"""coverage_collapse_alarm — CALLABLE level-2 inherited-blindness detector for a kreditgate (H, for I; epoch coordinate
'level-2 inherited blindness I/H'). Packages the deployable detector proven in H's cells (b7338638e -> c5e3be727 ->
738cf2fcc, CUSUM at 0.045 false-alarm / power 1.0, credited deployable in D batch).

WHAT IT DETECTS: recursive coverage-collapse (model-collapse) of a data-generation loop. A corpus that is repeatedly
regenerated by a model trained on its own output UNDER-covers a Fisher null that COMPOUNDS across generations -- measured
as sigma_min(feature-covariance) collapsing toward 0. This raises a CALIBRATED alarm (D batch/batch matched-null rule:
a naive/white null over-detects, so the baseline is a MATCHED iid-fresh null; the sequential CUSUM correction gives a
nominal false-alarm instead of the multiple-comparison-inflated any-exit rule).

SUBSTRATE-AGNOSTIC: the caller supplies (a) `sigma_min_of(sample) -> float` (e.g. min-eig of the feature covariance) and
(b) `draw_true(n) -> sample` (an iid draw from the TRUE distribution, for the matched-null baseline + OED refill). Plug in
your corpus's per-generation sigma_min trajectory; get {fired, latency,...}. CLASS-3 origin: tune `h` on your own null.

  from graph_engine.coverage_collapse_alarm import calibrate_threshold, matched_null_baseline, cusum_alarm
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Sequence

import numpy as np

K_SLACK_DEFAULT = 0.5          # CUSUM reference value (drift allowance in sd units); standard tuning
TARGET_FALSE_ALARM = 0.05


@dataclass
class CollapseAlarm:
    fired: bool
    latency_gen: int           # generation at which CUSUM crossed the threshold (-1 if never)
    cusum_path: list[float]
    threshold: float
    baseline_mean: list[float]
    baseline_sd: list[float]
    nonfinite_gens: list[int]  # generations where sigma_traj/baseline was NaN/inf -- forced-fire, see cusum_alarm


def matched_null_baseline(sigma_min_of: Callable[[np.ndarray], float],
                          draw_true: Callable[[int], np.ndarray],
                          n_per_gen: int, gens: int, runs: int = 300,
                          rng: np.random.Generator | None = None) -> tuple[np.ndarray, np.ndarray]:
    """MATCHED null: each generation an iid FRESH draw from the true distribution (NO inheritance). Returns the per-
    generation (mean, sd) of sigma_min under no-collapse -- the correct baseline (batch: match the null, don't whiten)."""
    rng = rng or np.random.default_rng(0)
    traj = np.array([[sigma_min_of(draw_true(n_per_gen)) for _ in range(gens + 1)] for _ in range(runs)])
    return traj.mean(0), traj.std(0) + 1e-9


def cusum_alarm(sigma_traj: Sequence[float], baseline_mean: Sequence[float], baseline_sd: Sequence[float],
                threshold: float, k_slack: float = K_SLACK_DEFAULT) -> CollapseAlarm:
    """One-sided CUSUM on a sigma_min-per-generation trajectory vs the matched-null baseline. Accumulates the shortfall
    of sigma_min below baseline (in sd units); fires when the cumulative sum exceeds `threshold`. Nominal false-alarm
    (vs the multiple-comparison-inflated any-exit rule).

    ★FAIL-CLOSED on non-finite input (self-audit sweep): `max(0.0, S + shortfall)` where `shortfall` is NaN
    silently evaluates to `0.0` in Python (`max(0.0, nan) == 0.0`, since any comparison with NaN is False) -- a
    degenerate/unmeasurable generation (sigma_min_of returning NaN, or a zero-variance baseline) would be silently
    absorbed as "no shortfall this generation" instead of the alarm-worthy event it actually is (an unmeasurable
    coverage state is at least as bad as the worst measured one, matching thermal_runaway_severity_cert's pessimistic-
    on-unknown convention in this same repo). Fix: a non-finite sigma_traj[g]/bm[g]/bs[g] is recorded in
    `nonfinite_gens` and forces the alarm to fire at that generation (or earlier, if a real crossing already occurred)
    -- it can never SUPPRESS or DELAY a fire, only force or advance one."""
    bm, bs = np.asarray(baseline_mean, float), np.asarray(baseline_sd, float)
    S = 0.0; path = [0.0]; latency = -1; nonfinite_gens: list[int] = []
    for g in range(1, len(sigma_traj)):
        if not (np.isfinite(sigma_traj[g]) and np.isfinite(bm[g]) and np.isfinite(bs[g])):
            nonfinite_gens.append(g)
            path.append(float("nan"))
            if latency < 0:
                latency = g
            continue
        S = max(0.0, S + (bm[g] - sigma_traj[g]) / bs[g] - k_slack)
        path.append(float(S))
        if latency < 0 and S > threshold:
            latency = g
    return CollapseAlarm(fired=latency >= 0, latency_gen=latency, cusum_path=path,
                         threshold=float(threshold), baseline_mean=list(map(float, bm)), baseline_sd=list(map(float, bs)),
                         nonfinite_gens=nonfinite_gens)


def calibrate_threshold(sigma_min_of: Callable[[np.ndarray], float],
                        draw_true: Callable[[int], np.ndarray],
                        n_per_gen: int, gens: int,
                        baseline_mean: Sequence[float], baseline_sd: Sequence[float],
                        target_false_alarm: float = TARGET_FALSE_ALARM, runs: int = 300,
                        k_slack: float = K_SLACK_DEFAULT,
                        rng: np.random.Generator | None = None) -> float:
    """Calibrate the CUSUM threshold h on FRESH matched-null runs so the false-alarm rate ~= target (nominal 0.05)."""
    rng = rng or np.random.default_rng(1)
    null_runs = [np.array([sigma_min_of(draw_true(n_per_gen)) for _ in range(gens + 1)]) for _ in range(runs)]
    hs = np.linspace(0.5, 10.0, 80)
    fa = np.array([np.mean([cusum_alarm(t, baseline_mean, baseline_sd, h, k_slack).fired for t in null_runs]) for h in hs])
    return float(hs[int(np.argmin(np.abs(fa - target_false_alarm)))])


def oed_refill_targets(current_sample: np.ndarray, candidate_pool: np.ndarray, n_collect: int) -> np.ndarray:
    """THE FIX side of the alarm (E-opt OED active-collection): once collapse is detected, which points should the
    kreditgate COLLECT from the true distribution to re-cover the Fisher null? Returns the indices (into candidate_pool)
    of the n_collect candidates that most reduce the coverage deficit -- greedily the FARTHEST-from-current points
    (max-min-distance = the under-covered / high-leverage region = batch's shared low-texture floor). Deterministic.

    Greedy max-min (farthest-point) is the standard cheap E-opt surrogate: each pick maximizes the minimum distance to
    the already-covered set, so it fills the largest coverage hole first -> raises sigma_min of the augmented covariance.
    """
    cur = np.asarray(current_sample, float); pool = np.asarray(candidate_pool, float)
    if len(pool) == 0 or n_collect <= 0:
        return np.array([], dtype=int)
    # (self-audit, mirrors the bare-array-reduction-form sweep -- the class the AST lint structurally
    # cannot see, a plain reduction over a runtime array with no comprehension/mask-subscript): the len(pool)==0
    # guard above did NOT cover len(cur)==0 (a legitimate cold-start: no prior sample collected yet). Reproduced
    # live: np.min over the empty axis=1 slice raised "zero-size array to reduction operation minimum has no
    # identity". Cold start has no natural "distance to covered set" -- treat every candidate as EQUALLY
    # uncovered (dmin=+inf) so the greedy loop below degrades to maximize spread WITHIN the pool itself, a
    # well-defined and reasonable first-batch selection rather than a crash.
    # (self-audit, triggered by the mechanized degeneracy-fail-open lint P2, re-swept this module's OTHER
    # bare argreduce beyond): a NaN-coordinate `pool` candidate is silently PREFERRED by argmax (NaN
    # propagates through the max-min distance as if maximal), so the OED-refill recommendation would tell the
    # kreditgate to "collect" an already-unmeasurable candidate -- reproduced live, a single NaN row was picked
    # FIRST. Worse: a NaN row in `cur` (an already-collected reference point) corrupts np.min over EVERY
    # candidate's distance row (NaN propagates through the reduction), silently degrading the ENTIRE greedy
    # selection to an arbitrary near-sequential pick, not just one bad candidate -- reproduced live. Fix: drop
    # non-finite `cur` rows before computing distances (a corrupted reference point is not "covered", the safe/
    # cold-start-consistent direction), and permanently exclude non-finite `pool` rows from ever being argmax'd
    # (re-applied every iteration, since np.minimum can reintroduce NaN into an already -inf'd slot).
    if len(cur) > 0:
        cur = cur[np.all(np.isfinite(cur), axis=1)]
    pool_finite = np.all(np.isfinite(pool), axis=1)
    if len(cur) == 0:
        dmin = np.full(len(pool), np.inf)
    else:
        # min distance of each candidate to the current (covered) set
        dmin = np.min(np.linalg.norm(pool[:, None, :] - cur[None, :, :], axis=2), axis=1)
    dmin = np.where(pool_finite, dmin, -np.inf)
    picked: list[int] = []
    for _ in range(min(n_collect, int(pool_finite.sum()))):
        j = int(np.argmax(dmin)); picked.append(j)
        # update: candidates now also compete with the just-picked point (farthest-point/maxmin coverage)
        dj = np.linalg.norm(pool - pool[j][None, :], axis=1)
        dmin = np.minimum(dmin, dj)
        dmin = np.where(pool_finite, dmin, -np.inf)   # re-exclude non-finite candidates every iteration
        dmin[j] = -np.inf
    return np.array(picked, dtype=int)


__all__ = ["CollapseAlarm", "matched_null_baseline", "cusum_alarm", "calibrate_threshold",
           "oed_refill_targets", "K_SLACK_DEFAULT", "TARGET_FALSE_ALARM"]
